package com.demo.oauth.model.sys;

import com.demo.oauth.model.base.BaseEntity;

public class SysUserPrivilege extends BaseEntity<SysUserPrivilege> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_privilege.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_privilege.privilege
     *
     * @mbg.generated
     */
    private String privilege;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_privilege.user_id
     *
     * @return the value of sys_user_privilege.user_id
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_privilege.user_id
     *
     * @param userId the value for sys_user_privilege.user_id
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_privilege.privilege
     *
     * @return the value of sys_user_privilege.privilege
     * @mbg.generated
     */
    public String getPrivilege() {
        return privilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_privilege.privilege
     *
     * @param privilege the value for sys_user_privilege.privilege
     * @mbg.generated
     */
    public void setPrivilege(String privilege) {
        this.privilege = privilege == null ? null : privilege.trim();
    }
}